#!/bin/bash


gcc_version='slc7_amd64_gcc700'
CMSSW_version='CMSSW_10_2_13'


source /cvmfs/cms.cern.ch/cmsset_default.sh
export SCRAM_ARCH=$gcc_version
export VO_CMS_SW_DIR=/cvmfs/cms.cern.ch

if [ ! -d $CMSSW_version ]; then cmsrel $CMSSW_version; fi;
cd $CMSSW_version/src
cmsenv

